// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZw6O-BcaXfkKQd8o6MvpHEuoh_Mcb3_U',
    appId: '1:602124530547:web:87217b766071bd30d5cb06',
    messagingSenderId: '602124530547',
    projectId: 'truckventory-79e22',
    authDomain: 'truckventory-79e22.firebaseapp.com',
    storageBucket: 'truckventory-79e22.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASEtq_kp1bqj4WTRdAZnffEq5X6gePIZc',
    appId: '1:602124530547:android:d95f6e88221bb742d5cb06',
    messagingSenderId: '602124530547',
    projectId: 'truckventory-79e22',
    storageBucket: 'truckventory-79e22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgOLc_ITBslqpSQGNQrz2tZKzLx3B5Pww',
    appId: '1:602124530547:ios:dfa1bd22bcc52c9fd5cb06',
    messagingSenderId: '602124530547',
    projectId: 'truckventory-79e22',
    storageBucket: 'truckventory-79e22.firebasestorage.app',
    iosBundleId: 'com.example.truckventory',
  );
}
